### ISSUE TITLE
Desktop app automatisch builden bij elke nieuwe versie

### ISSUE THREAD

**Issue by jpkleemans** [VEZwolle/vezy-worship#10]
GitHub action voor `npm run electron:build` maken

**Comment by J76F** [comment]
https://github.com/Qoyyuum/quasar-devops/blob/master/action-quasar-electron-build.yaml

**Comment by J76F** [comment]
Zie test: https://github.com/J76F/quasar-electron-action-update
uitleg in de readme --> github, action voor build + release + autoupdate + eventueel notificatie
(--> In build ook publish zetten hiervoor.)
