### ISSUE TITLE
Klok kunnen weergeven

### ISSUE THREAD

**Issue by jpkleemans** [VEZwolle/vezy-worship#17]

**Comment by J76F** [comment]
[optie_voor_klok_bij_counddown.zip](https://github.com/VEZwolle/vezy-worship/files/8985239/optie_voor_klok_bij_counddown.zip)
Keuze optie om aftelklok of klok(tijd) weer te geven tot ingestelde tijd; verdwijnt daar na.
(tekst in invoer vak wijzgt ook mee.)
