### ISSUE TITLE
Liedregels automatisch teruglopen indien te lang voor het scherm

### ISSUE THREAD

**Issue by jpkleemans** [VEZwolle/vezy-worship#20]

**Comment by J76F** [comment]
Automatische terugloop geeft nadelen in aantal weer te geven regels bij songs. Wordt niet defineerbaar, en projecteur ziet niet snel dat hij hier aanpassingen moet doen om zelf een goede plek voor afbreken te kiezen. 

Vertaling zal ook niet altijd op zelfde plek gesplitst worden.

Keuze voor nu is dit niet toe te passen.
J & JP
