### ISSUE TITLE
Transparantie in afbeeldingen ook transparant maken in alpha channel

### ISSUE THREAD

**Issue by jpkleemans** [VEZwolle/vezy-worship#29]

**Comment by J76F** [comment]
Is een bibliotheek met de Apache License compentabel is met onze?
Anders lijkt onderstaande wel een mooie snelle optie/bibliotheek om alpha channel image te maken uit foto met transparantie.
`npm install sharp`
zie: https://sharp.pixelplumbing.com/api-channel

ensureAlpha --> toevoegen van alpha channel aan foto.
door waarde 0-1 in te vullen kan je hoeveelheid transparantie aangeven wanneer nog niet aanwezig.
```
// rgba.png will be a 4 channel image with a fully-opaque alpha channel
await sharp('rgb.jpg')
  .ensureAlpha()
  .toFile('rgba.png')
```
extractChannel --> kleurkanaal uit foto halen. (red, green, blue or alpha)
```
// alpha.jpg is a greyscale image containing the green channel of the input
await sharp(input)
  .extractChannel('alpha')
  .toFile('alpha.jpg');
```
Gecombineerd kom je dan denk ik hier op uit. (moet nog testen)
```
await sharp('rgb.jpg').ensureAlpha().extractChannel('alpha').toFile('alpha.jpg');
```

Met deze bibliotheek kan je ook resize, mogelijk dan voor #45.
