### ISSUE TITLE
Uren op de countdown correct weergeven

### ISSUE THREAD

**Issue by jpkleemans** [VEZwolle/vezy-worship#30]
's morgens vroeg als ik aan kom dus 2 uur van te voren oid. dan zie je nu 180:00 staan ipv 2:00:00.

**Comment by J76F** [comment]
[countdown.zip](https://github.com/VEZwolle/vezy-worship/files/8964823/countdown.zip)
Geen idee hoe ik ze makkelijk kan uploaden; mag je maandag wel laten zien.
Countdown aangepast dat uren worden weergegeven wanneer meer dan 60 min. en tekst verduidelijkt dat hat alleen voor dezelfde dag in de toekomst wordt weergegeevn.
