### ISSUE TITLE
Als databasebeheerder lied toevoegen/wijzigen aan de liederen database

### ISSUE THREAD

**Issue by jpkleemans** [VEZwolle/vezy-worship#4]
- [x] lokale database
- [x] cloud database

Onderdelen:
- [x] Aanmaken, wijzigen, verwijderen van liederen
- [ ] URL vezy-worship.web.app/#/liederen
- [x] Beschermd met wachtwoord

**Comment by J76F** [comment]
lokale database --> iedereen kan toevoegen. (wordt vervangen in database; niet extra toegevoegd nu)
- Via save pulldown --> toevoegen database
- Via settings of via song toevoegen: bewerken/verwijderen liederen

**Comment by J76F** [comment]
algolia ipv firebase gebruikt
