### ISSUE TITLE
Als projecteur lied inladen vanuit de liederen database

### ISSUE THREAD

**Issue by jpkleemans** [VEZwolle/vezy-worship#5]
- [x] lokale database
- [x] cloud database

Onderdelen:
- [ ] Firestore tabel aanmaken
  - id (genereerd firestore voor je)
  - title
  - text
  - translation
  - collection (nullable)
  - number (nullable)
  - creator
  - created_at
  - updated_at
- [ ] API endpoint aanmaken: `GET /songs`
- [ ] Bij SongEditDialog een tabblad toevoegen "database"
- [ ] Zoekbalk (in eerste instantie alleen op `title` en `number` zoeken)
- [ ] Dropdown keuzemenu op collectie (bundel) om te filteren op bijv. Opwekking of Hillsong oid
- [ ] Zodra je begint met typen liederen inladen in lijst (bij min 3 letters, debounce van 500ms)
- [ ] Zodra je op een lied klikt zie je rechts het voorbeeld
- [ ] Tabblad vertaling indien van toepassing
- [ ] Knop "Gebruik deze liedtekst" -> lied kopieeren naar eerste tabblad en direct opslaan in setlist
- [ ] Uitzoeken hoe duur dit wordt in Firestore

**Comment by J76F** [comment]
@jpkleemans is er een handig (centraal) database systeem die we vanaf internet kunnen benaderen. Zodat iedereen dezelfde kan gebruiken, eventueel in sharepoint omgeving of is er op de webapp site iets? Denk wel handig dat hij beschermd is voor gebruik door ons.

**Comment by J76F** [comment]
[songs2.zip](https://github.com/VEZwolle/vezy-worship/files/10094842/songs2.zip)
update van database bestand (in sql en json) formaat; tbv importen in firestore.
Heb de titel gesplitst nu zoals besproken met collectie, nummer en titel.
tevens nog wat verdwaalde fontsnamen verwijderd uit liedtekst .

**Comment by J76F** [comment]
Ben de database van EW aan opsplitsen EN/NL liederen; laat even waten als je wilt importeren, dan stuur ik je de recenste versie.
(direct mooie test voor song editor, met taalherkenning ;-)

**Comment by J76F** [comment]
[songs.zip](https://github.com/VEZwolle/vezy-worship/files/10316430/songs.zip)
JSON formaat van de song export waarbij NL & EN in aparte kolommen staan en collecties.
bij nummer staat -v- wanneer vertaling aanwezig is; wanneer (geen vertaling) staat is deze alleen in andere taal beschikbaar.
Denk dat ik de meeste nu heb gesplitst.
Nog niet de opmaak verder aangepast naar 4 regels per sheet maar verwacht dat de moderne die vanuit EW zelf al we hadden.

**Comment by J76F** [comment]
misschien een optie?
https://www.algolia.com/developers/firebase-search-extension/
(een opensoure/no-profit free regeling)

**Comment by J76F** [comment]
Budget/Budget alert instellen firebase:

https://firebase.google.com/docs/projects/billing/avoid-surprise-bills#set-up-budget-alert-emails

https://cloud.google.com/billing/docs/how-to/budgets?hl=en&authuser=0

https://console.firebase.google.com/project/vezy-worship/usage/details

https://blog.minimacode.com/cap-firebase-spending/

**Comment by J76F** [comment]
[song-database](https://github.com/VEZwolle/vezy-worship/tree/song-database) --> via local gezipt json bestand werkt zoeken.
[song-database-locationsave](https://github.com/VEZwolle/vezy-worship/tree/song-database-locationsave) --> bovenstaand, maar dan in electron niet elke keer opgave bestandslocatie [inlezen nog uitzoeken]

**Comment by J76F** [comment]
algolia ipv firebase gebruikt
