### ISSUE TITLE
Hoogte letters

### ISSUE THREAD

**Issue by J76F** [VEZwolle/vezy-worship#73]
Ik vindt zelf met name de titels moeilijk leesbaar, klein en bij veel tekst verlies ik het overzicht; In iets mindere mate heb ik dat met de vertalingen ook; Vandaar wat onderzoek bij de TV makers wat die doen ter vergelijk en lering. (niet iedereen heeft een mega scherm waar ook nog eens heel dichtbij gezeten wordt.)

Heb wat zitten meten op print screen TV en documentatie gevonden van ntr: over letterhoogten.
Soms wat moeilijk vertalen van pt naar px omdat je niet de om reken factor weet (lijkt een ander dan standaard te hebben 12pt=16px te hebben). zie bijlage
[Letterhoogte ntr.pdf](https://github.com/VEZwolle/vezy-worship/files/9193571/Letterhoogte.ntr.pdf)
)
uitkomst:
- Ondertitels: 4,0 a 4,5vw / regelhoogte: 4,5 a 5,0vw (en outline 4px)
- titels (kop) op 2,3 a 2,6vw, titels (tekst) op 2,9 a 3,15vw, regelhoogte 3,15vw

Wij gebruiken nu:
- Song, livestream:  3,8vw (3,0vw vertaling) / regelhoogte 4,4vw
- Title, livestream: kop 1,3vw, tekst 1,7vw, regelhoogte 2,2vw

Wij zitten met name bij de titel nu een stuk kleiner; en de song een klein beetje.

_Voorstel om eea wat groter te maken voor met name de titels.
Basis: kop op 2,4vw en tekst op 3,0vw
Bij veel tekst (schriftlezing bijv.): kop op 2,6vw en tekst op 3,8vw (gelijk song)_

- [x] Overleg welke grote wijs is.
- [x] Keuze afmetingen
- [x] Toepassen bij de verschillende presentatie typen

**Comment by jpkleemans** [comment]
Top uitzoekwerk! Eens dat de teksten bij met name de ondertitels te klein zijn. Misschien goed om een keer in de hal te kijken wat de beste grootte is

**Comment by J76F** [comment]
Lijkt me goed om keer in hal te kijken. Kevin er dan ook bij vragen om de keuzes dan vast te leggen.
Misschien ook goed om vooraf even wat tv-groten icm kijkafstand te inventariseren. met name ook de kleinere.

In bijlage nog document over letterhoogten tov kijkafstanden. (heeft Frank eens opgezocht (audio stream))
![image](https://user-images.githubusercontent.com/105970388/187096171-313d35e2-b441-46ac-89d0-d424c578895f.png)
[Ergonomie - informatiepresentatie conform NEN-3087.pdf](https://github.com/VEZwolle/vezy-worship/files/9440525/Ergonomie.-.informatiepresentatie.conform.NEN-3087.pdf)

**Comment by J76F** [comment]
Uitkomst overleg: Template beamer
[Projectie template Samen verlangen naar Jezus v03.pptx](https://github.com/VEZwolle/vezy-worship/files/10212169/Projectie.template.Samen.verlangen.naar.Jezus.v03.pptx)

Song: Hoogten oke zoals nu ingesteld.
- Beamer maximaal 4 regels: (4x NL of 2xEN+2xNL met tussenafstand)
- Livestream 2 regels: (2x NL of 1xEN + 1xNL)

Caption/Scripture:
Beamer 
- --> zie PPT; nog omrekenen.
-  (bij bijbeltekst titelblok onder op vaste positie.; zie ook andere opties van weergave. (ubuntu 32pt, regelafstand 42pt)
- links uitlijnen ipv uitvullen

Livestream 
- --> titel goed --> uitlijnen naar tekst (nieuwe positie); 
- tekst naar 2.2vw/regel 2.7vw ; padding tekst in blok 2vw 2vw 1.5vw 2vw; en padding tekstblok 5 ipv 6vw
- 2 types: onder vaste breedte of onder afhankelijk lengte tekst.
- bij scripture: max 3 regels; blok op vaste grote houden bij doorlopen tekst. (zie max tekst grote die langs komt.)
