### ISSUE TITLE
scripture | Input box hoofdstuk, vers kan negatief zijn

### ISSUE THREAD

**Issue by J76F** [VEZwolle/vezy-worship#75]
Bij input setting:
De +/- pijltjes gaan verder omlaag dan vers 0 | Instellen dat deze niet onder de 1 kan komen (negatieve verzen en hoofstukken bestaan niet.)

**Comment by jpkleemans** [comment]
![image](https://user-images.githubusercontent.com/5700014/187026588-492f5275-24e2-4935-b31d-efc5ecb4b1fc.png)
Deze bedoel je? Ja goed punt

**Comment by J76F** [comment]
klopt

**Comment by J76F** [comment]
Of keuzenlijst uit de hoofdstukken/verzen die in dat boek bestaan.
