### ISSUE TITLE
Scrollbars kort te zien bij afbeelding preview

### ISSUE THREAD

**Issue by jpkleemans** [VEZwolle/vezy-worship#86]

**Comment by J76F** [comment]
Lijkt alleen in de .exe voor te komen en niet in de web-app/vs-code

**Comment by J76F** [comment]
Maat image is gelijk; bij inladen staat hij alleen ca. 5vh naar rechts en onder geschoven waarna hij op de juiste plek komt te staan en scrollbars weer weg zijn.

![image 2](https://github.com/VEZwolle/vezy-worship/assets/105970388/d85fd0c8-3f76-48de-aebe-9565780aced8)
![image 3](https://github.com/VEZwolle/vezy-worship/assets/105970388/f3b21548-0829-4c38-b1bb-1c24068b361f)

**Comment by J76F** [comment]
Gebeurt zowel bij image control als ook bij de preview boxen onderin wanneer je er 1 uit en weer aan zet op moment dat een image wordt getoond.

**Comment by J76F** [comment]
Is er optie eerst wachten op volledig geladen voor tonen?

**Comment by J76F** [comment]
Zelfde gebeurt nu met preview in setting bij caption/scripture wanneer je wijzigde tussen de verschillende slides/update teksten.
(lijkt wel tijdelijk een stukje tekst naast te komen staan die daarna weer weg is.)

**Comment by J76F** [comment]
beide maken gebruik van component: OutputPreview --> onderdeel output

De box onderin lijkt er geen last van te hebben als hij eenmaal staat (uit aan wel),  maken gebruik van component: OutputPreview --> output --> onderdeel output

Deze boxes staat ook tussen `<Transition name="q-transition--fade">` en de andere niet.
Maar mogelijk gaat het hier goed doordat alleen het _onderdeel output_ wijzigd dieper weg in het _output_ component, waardoor de basis blijft staan.

Zou je mogelijk de `key`  niet op `outputpreview` moeten zetten maar op onderstaand component via outputpreview, maar hoe doe je dat...

Of dat je de iframe pas vult na this.nextTik() zodat de plaats daaromheen al gerenederd is vooraf?

Maar vermoed beetje laatste dat iframe zijn maat/plek niet goed weet en pas na plaatsen gecorrigeerd wordt na juiste maat.

**Comment by J76F** [comment]
- `this.$nexttik(() => { ... })` geprobeerd om mounted deel, geeft geen verschil
- `this.$nexttik(() => { ... })` geprobeerd om app.mount deel, geeft geen verschil
- `<Transition name="q-transition--fade">` geprobeerd om Iframe, geen verschil
- width en heigth op 100% in css iframe werkt ook niet
- `v-show` toegevoegd aan iframe en nadat app.mount() is geweest op true --> geen verschil.
- `v-show` toegevoegd aan iframe en nadat app.mount() is geweest tussen een nextTick op true --> geen verschil.
- `v-show` toegevoegd aan iframe en nadat app.mount() is geweest en daar een debounce van 500 op --> gaat goed.
  - debounce van 100 ook goed
  - debounce van 10 gaat goed bij text-settings caption maar niet bij collecte sheet (image controll)
